### ISSUE TITLE
Deploying web app to Elastic Beanstalk 

### ISSUE THREAD

**Issue by cgddrd-gardin** [aws-samples/aws-iot-securetunneling-web-ssh#1]
Hi,

Do you happen to have any info on how to deploy this web app to Elastic Beanstalk?

Many thanks,

**Comment by alifrugal** [comment]
Hi, 

You don't need Elastic Beanstalk. You can deploy the web app on Amazon S3: 
https://techdirectarchive.com/2021/08/31/how-to-deploy-an-angular-app-to-aws-s3/

A link below as well if you want to use Cloudfront to serve it: 
https://aws.amazon.com/premiumsupport/knowledge-center/cloudfront-serve-static-website/

ps: this is how the demo is hosted: https://d27s40qf47wdc3.cloudfront.net/ (Cloudfront + S3)

**Comment by cgddrd-gardin** [comment]
Brilliant – many thanks for your help!

Connor Goddard
Tech Lead - Platform

Gardin Ltd
https://www.gardin.co.uk<https://www.gardin.co.uk/>

***@***.***
